config/routes.rb
Rails.application.routes.draw do



  resources :users do
    resources :items
  end

  resources :items do
    resources :measurements
  end

  resources :measurements

  get '/signup', to: "users#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"
  get "/auth/facebook/callback", to: "sessions#create_with_fb"
  root 'users#home'



  # get '/', to: "items#about"
  # get '/items', to: "items#index"
  # get '/items/:id', to: "items#show"
  # resources :items, only: [:index, :new]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :measurements
  has_many :users, through: :measurements
  # validates :name, {presence: {message: "!!!!!!!!!!not blank!!!!!!"}, uniqueness: {message: "must be unique!!!!!"}}
  validates_presence_of :name
  validates_uniqueness_of :name

  validate :is_title_case

  before_validation :make_title_case
  accepts_nested_attributes_for :measurements
  # validate :name_presence
  #
  # def measurements_attributes=(attr)
  #   attr.values.each do |m|
  #     new_m = Measurement.new(m)
  #       new_m.item = self
  #       # new_m.user = current_user
  #       new_m.save
  #     # if m[:id] == nil
  #     #   new_m = Measurement.new(m)
  #     #   new_m.item = self
  #     #   new_m.save
  #     # else
  #     #   new_m = Measurement.find_by(id: m[])
  #     #   new_m.update(m)
  #     # end
  #   end
  # end

  private

  def is_title_case
    if name != name.titlecase
      errors.add(:name, "must be titlecased")
    end
  end

  def make_title_case
    self.name = self.name.titlecase
  end
  # def name_presence
  #   if name == nil || name == "" || name == " "
  #     errors.add(:name, "cannot be empty!!!")
  #   end
  # end


end

app/models/measurement.rb
class Measurement < ApplicationRecord
  belongs_to :item
  belongs_to :user

  accepts_nested_attributes_for :item

  validates_presence_of :quantity

   scope :quantity_search, -> (search) { where("quantity >= ?", search) }

  # def item_attributes=(att)
  #
  # end

  # def self.quantity_search(search)
  #   self.where("quantity >= ?", search)
  # end

  def item_name=(name)
    self.item = Item.find_or_create_by(name: name)
  end

  def item_name
    self.item ? self.item.name : nil
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :measurements
  has_many :items, through: :measurements
  validates_presence_of :username
  validates_uniqueness_of :username
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user

  def require_login
    redirect_to '/' if !current_user
  end

  def redirect_if_logged_in
    redirect_to '/items' if current_user
  end

  def current_user
    @user = User.find_by(id: session[:user_id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  layout 'application'

  before_action :set_item, except: [:new, :create, :index]
  before_action :require_login

  def index
    if params[:user_id]
      @items = User.find_by(id: params[:user_id]).items
    else
      @items = Item.all
    end
  end

  def show
  end

  def new
    @item = Item.new
    @item.measurements.build(user: current_user)
  end

  def create
    @item = Item.create(item_params)
    if @item.save
      redirect_to item_path(@item)
    else
      # @errors = @item.errors.full_messages
      render :new
    end
  end

  def edit

  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@item)
    else
      # @errors = @item.errors.full_messages
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  private

  def set_item
    @item = Item.find_by(id: params[:id])
  end

  # def item_params(*args)
  #   params.require(:item).permit(args)
  # end

  def item_params
    params.require(:item).permit(:name, measurements_attributes: [:unit, :quantity, :id, :user_id])
  end

end

# {"name"=>"Brown Sugar", "measurements_attributes"=>{"0"=>{"quantity"=>"2", "unit"=>"Boxes"}}}
#
# def initialize(hash)
#   hash.each do |k, v|
#       self.send("#{k}=", v)
#   end
# end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :require_login

  layout 'application'

  def index
    if params[:search]
      @measurements = Measurement.quantity_search(params[:search])
    else
      @measurements = Measurement.all
    end
  end

  def new
    # binding.pry
    if params[:item_id]
      @item = Item.find_by(id: params[:item_id])
      @measurement = @item.measurements.build
    else
      @measurement = Measurement.new
      @measurement.build_item
    end

    # @items = Item.all
    # @item = @measurement.build_item
  end

  def create
    m = Measurement.new(measurement_params)
    m.user = current_user
    m.item_id = params[:item_id]
    m.save
    redirect_to item_path(m.item)
  end

  private

  def measurement_params
    params.require(:measurement).permit(:unit, :quantity, :item_id, :item_name, item_attributes: [:name])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :redirect_if_logged_in, except: [:destroy]

  def new
    # @errors = []
    # @user = User.new
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to items_path
    else
      @errors = ["Username or password incorrect"]
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end

  def create_with_fb
    user = User.find_or_create_by(username: auth["email"]) do |u|
        u.password = 'password'
    end
    user.save
    session[:user_id] = user.id

    redirect_to items_path
  end

  private

  def auth
    request.env['omniauth.auth']["info"]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :redirect_if_logged_in

  layout 'application'

  def new
      @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to items_path
      # redirect_to user_path(@user)
    else
      # @errors = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custom_form_builder.rb
class CustomFormBuilder < ActionView::Helpers::FormBuilder

  def my_fields_for(association, &block)
    association_attributes_method = "#{association}_attributes="
    object_class_downcase = @object.class.to_s.downcase
    association_attributes = "#{association}_attributes"
    object = @object
     if object.methods.include?(association.to_sym) && object.methods.include?(association_attributes_method.to_sym)
        object.send(association).each_with_index.map do |a, i|
            # binding.pry
          @object = a
          @index = i
          @object_name = "#{object_class_downcase}[#{association_attributes}][#{@index}]"
          # binding.pry
          yield(self, block)
          if @object.id
            hidden_field(:id)
          end
        end
     end.join("").html_safe
  end

end

app/helpers/measurements_helper.rb
module MeasurementsHelper

  def show_item_name(m, index)
    m.item.name if index
  end

  def form_url_helper(item)
    item ? item_measurements_path(item) : measurements_path
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_errors.erb
<% errors.each do |m|%>
  <li><%=m%></li>
<%end%>

app/views/items/_form.erb
<%=form_for @item do |f| %>
  <%= f.label "Name:" %>
  <%= f.text_field :name %><br>

  <%=f.label "Measurements" %><br>
  <%=f.fields_for :measurements do |m|%>
    <%= m.hidden_field :user_id%>
    <%=m.label :quantity%>
    <%=m.number_field :quantity %><br>
    <%=m.label :unit%>
    <%=m.text_field :unit%><br>
  <%end%>
  <%=f.submit%>
<%end%>

app/views/items/edit.erb
<%=render partial: "application/errors", locals: {errors: @item.errors.full_messages} %>

<%= render 'form' %>

app/views/items/index.erb
<h1>All Items!</h1>


<% @items.each do |i| %>
  <li><%= link_to i.name, item_path(i) %> </li>
<% end%>

app/views/items/new.erb
<%=render partial: "application/errors", locals: {errors: @item.errors.full_messages} %>
<%= render 'form' %>

app/views/items/show.erb
<h1>Item</h1>

<%=@item.name%><br><br>

<%= render partial: "measurements/measurements", locals: {measurements: @item.measurements, index: false} %>
<br><br>

<%= link_to "Add Item to Pantry", new_item_measurement_path(@item) %><br><br>

<%=link_to "Edit", edit_item_path(@item)%><br><br>

<%=button_to "Delete", @item, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPantry</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if current_user%>
      <%=link_to "All Items", items_path%>
      <%=link_to "My Pantry", user_items_path(current_user)%>
      <%=link_to "New Item", new_user_item_path(current_user)%>
      <%=link_to "New Measurement", new_measurement_path%>
      <%=link_to "Logout", logout_path, method: :post%>
    <%else%>
      <%= link_to "Sign Up", signup_path %>
      <%= link_to "Log In", login_path %>
      <%=link_to "Sign in with Facebook", '/auth/facebook'%>
    <%end%>

    <%= yield %>
  </body>
</html>

app/views/layouts/items.html.erb
<body>
  <h2>Item Layout</h2>
  <%=link_to "All Items", items_path%>
  <%=link_to "My Pantry", user_items_path(current_user)%>
  <%=link_to "New Item", new_item_path%>
  <%=link_to "New Measurement", new_measurement_path%>
  <%= yield %>
</body>

app/views/layouts/measurements.html.erb
<body>
  <h2>Measurement Layout</h2>
  <%=link_to "All Items", items_path%>
  <%=link_to "New Item", new_item_path%>
  <%=link_to "New Measurement", new_measurement_path%>
  <%= yield %>
</body>

app/views/measurements/_form.erb
<%=form_for @measurement, url: form_url_helper(@item) do |f|%>
  <%=f.label :quantity%>
  <%=f.number_field :quantity %>
  <%=f.label :unit%>
  <%=f.text_field :unit%>

  <% if !@item %>
    <%=f.label :item %><br>
    <%=f.fields_for :item do |i|%>
      <%=i.label :name %>
      <%=i.text_field :name %>
    <%end%>

  <%end%>



  <%=f.submit "Create Measurement"%>

<%end%>

app/views/measurements/_measurements.erb
<%measurements.each do |m|%>
  <li><%=m.quantity%> <%=m.unit%> <%= show_item_name(m, index)%></li>
<%end%>

app/views/measurements/edit.erb
<%=render 'form'%>

app/views/measurements/index.erb
<%=form_with url: measurements_path, method: :get do |f| %>
  <%=f.label "Search by quantity"%>
  <%=f.text_field :search%>
  <%=f.submit :search%>
<%end%>

<%=render partial: "measurements", locals: {measurements: @measurements, index: true}%>

app/views/measurements/new.erb
<% if @item %>
  <h4>Add <%=@item.name%> to your Pantry</h4>
<%end%>

<%=render 'form'%>

app/views/users/home.erb
<h1>Welcome!</h1>

app/views/users/new.erb
<h1>Sign Up</h1>

<%=render partial: "application/errors", locals: {errors: @user.errors.full_messages} %>

<%=form_for @user do |f| %>
  <%=f.label :username %>
  <%=f.text_field :username %>
  <%=f.label :password %>
  <%=f.password_field :password %>
  <%=f.label :password_confirmation %>
  <%=f.password_field :password_confirmation %>
  <%=f.submit%>
<%end%>